Initial C# Example Implementation
highlight-slm/webhook-transforms-slack pull request #3
Opened 2020-03-20 19:54 UTC by shortbloke

2020-03-23 20:26 UTC, DarrenKurn commented
Hi. I've added a bunch of comments. The below is the refactoring of the
main file, I have not run this anywhere. It builds, but that's about all I
can say atm

using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Highlight.WebHookParserFunction
{
    public static class HttpTriggerCSharp
    {
        [FunctionName("HttpTriggerCSharp")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route
= null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a
request.");
            // Local execution setting in local.settings.json
            // Azure execution setting configuration -> Applicaiton settings
            var slackWebHookUrl =
Environment.GetEnvironmentVariable("SLACK_WEBHOOK_URL");
            dynamic data = JsonConvert.DeserializeObject(await new
StreamReader(req.Body).ReadToEndAsync());

            if (data == null)
            {
                log.LogInformation("Invalid input data");
                return new BadRequestResult();
            }

            var message = SlackMessage
                .Create(data)
                .ToString();

            if (await PostSlackMessage(message, slackWebHookUrl, log))
            {
                log.LogInformation("Webhook successfully sent to Slack");
                return new OkResult();
            }
            else
            {
                log.LogInformation("Error sending Webhook");
                return new BadRequestResult();
            }
        }

        public static async Task<bool> PostSlackMessage(string message,
string slacklUrl, ILogger log)
        {
            var body = new StringContent(message, Encoding.UTF8,
"application/json");

            try
            {
                var response = await new HttpClient().PostAsync(slacklUrl,
body);

                if (response.IsSuccessStatusCode)
                {
                    return true;
                }
                else
                {
                    log.LogWarning($"Webhook send failed. Status code:
{response.StatusCode}. Message: {await
response.Content.ReadAsStringAsync()}");
                }
            }
            catch (Exception ex)
            {
                log.LogError($"Webhook send failed: {ex.Message}");
            }

            // If we got here, something went wrong!
            return false;
        }

        public class SlackAttachment
        {
            private SlackAttachment() { }

            public string color { get; set; }
            public string title { get; set; }
            public string text { get; set; }
            public string markdown_in { get; set; }

            public static SlackAttachment Create(dynamic payload)
            {
                if (payload == null)
                {
                    throw new ArgumentNullException(nameof(payload));
                }

                var highlightAlert = HighlightAlert.Create(payload.Problem);

                SlackAttachment attachment = new SlackAttachment
                {
                    title = $"{highlightAlert.direction}
{payload.alertSummary}",
                    text = $"{payload.problem} - <{payload.linkUrl}|More
information>",
                    color = highlightAlert.color,
                    markdown_in = "title, text"
                };

                return attachment;
            }
        }

        public class SlackMessage
        {
            private SlackMessage() { }

            public string text { get; set; }
            public IEnumerable<SlackAttachment> attachments { get; set; }
            public string mrkdown { get; set; }

            public override string ToString()
            {
                return JsonConvert.SerializeObject(this);
            }

            public static SlackMessage Create(dynamic payload)
            {
                if (payload == null)
                {
                    throw new ArgumentNullException(nameof(payload));
                }

                SlackMessage message = new SlackMessage
                {
                    text = "Highlight Alert",
                    attachments = new SlackAttachment[] {
SlackAttachment.Create(payload) },
                    mrkdown = "True"
                };

                return message;

            }
        }

        public class HighlightAlert
        {
            private HighlightAlert() { }

            public string color { get; set; }
            public string direction { get; set; }

            public static HighlightAlert Create(string problem)
            {
                if (string.IsNullOrWhiteSpace(problem))
                {
                    throw new ArgumentNullException(nameof(problem));
                }

                string color = string.Empty;
                string direction = ":grey_question:";

                string pattern = @"(\w+) alert (\w+)";
                Match match = Regex.Match(problem.ToLower(), pattern,
RegexOptions.IgnoreCase);

                if (match.Success)
                {
                    var highlightColor = match.Groups[1].Value;
                    var highlightDirection = match.Groups[2].Value;

                    if (highlightDirection == "raised")
                    {
                        direction = ":warning:";

                        if (highlightColor == "red")
                        {
                            color = "danger";
                        }
                        else if (highlightColor == "amber")
                        {
                            color = "warning";
                        }
                    }
                    else if (highlightDirection == "cleared")
                    {
                        color = "good";
                        direction = ":heavy_check_mark:";
                    }
                }

                return new HighlightAlert
                {
                    color = color,
                    direction = direction
                };
            }
        }
    }
}

On Mon, 23 Mar 2020 at 18:16, Martin Rowan <notifications@github.com> wrote:

> @shortbloke <https://github.com/shortbloke> requested your review on: #3
> <https://github.com/highlight-slm/webhook-transforms-slack/pull/3>
> Initial C# Example Implementation.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/highlight-slm/webhook-transforms-slack/pull/3#event-3156475843>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALJCOPF7TTI3CFEIT5PARTLRI6RPPANCNFSM4LQTMFQQ>
> .
>

2020-03-24 09:27 UTC, DarrenKurn requested changes
See inline comments?

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +        private static readonly HttpClient httpClient;
This shouldn't need to be static, as it is only used once

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +            httpClient = new HttpClient ();
As above, this need only be instantiated when it is needed.

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +            if (!string.IsNullOrEmpty (Convert.ToString (data))) {
'data' is already being converted to an object. Why convert is back to a string to check if it is empty? Better to do the convert (above) and then check for the data variable being null.

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +            SlackMessage message = new SlackMessage ();
Personally, I prefer
`var message = new SlackMessage
{
  text = "Highlight Alert",
  etc
}`

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +        public static async Task<HttpResponseMessage> PostSlackMessage (string message, string slacklUrl) {
This could probably just return a boolean as to whether the function passed or failed. If you are bothered about the actual exception message, either bubble up the exception (remove the try..catch), or have an out parameter containing the message.

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +            StringContent body = new StringContent (message, Encoding.UTF8, "application/json");
When declaring variables, if you are newing up an object, just use var for the variable
`var body = new StringContent(message.......etc)`

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +                responseMessage = await httpClient.PostAsync (uri, body);
Rather than interrogating responseMessage, return responseMessage.IsSuccessful

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +            if (!string.IsNullOrEmpty (problem)) {
use string.IsNullOrWhiteSpace(), because it could just be a long line of spaces

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +        private static HighlightAlert GetStatus (string problem) {
I would probably refactor this out so it is a create method on the HighlightAlert object

2020-03-24 09:27 UTC, DarrenKurn commented on CSharp/HttpTriggerCSharp.cs
> +            [HttpTrigger (AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
Should this be only POST?

2020-03-24 10:29 UTC, shortbloke commented on CSharp/HttpTriggerCSharp.cs
> +            StringContent body = new StringContent (message, Encoding.UTF8, "application/json");
So this when the type can be clearly inferred when newing it up, var is ok. Got it.

2020-03-24 13:32 UTC, shortbloke commented on CSharp/HttpTriggerCSharp.cs
> +        private static readonly HttpClient httpClient;
As testing has shown it's not used once it the Azure function stays spun up when it's called and can be used to handle multiple incoming requests.

2020-03-24 13:33 UTC, shortbloke commented on CSharp/HttpTriggerCSharp.cs
> +            httpClient = new HttpClient ();
To avoid perf/scale issue, covered here `https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/`

2020-03-24 13:41 UTC, shortbloke commented on CSharp/HttpTriggerCSharp.cs
> +            [HttpTrigger (AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
That was the default template for all the example webhooks. I'll check to see if just `post` works.

2020-03-24 13:48 UTC, shortbloke commented on CSharp/HttpTriggerCSharp.cs
> +            [HttpTrigger (AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
Removed Get. Will go back and change the other language examples too.

2020-03-24 14:32 UTC, merged